In [1]:
import pandas as pd

In [2]:
submissions = pd.read_json("./latest_competition_prediction.json")

In [3]:
def determine_subchallenge(data):
    sub = data["test"]
    if "Ligand Pose" in sub.keys():
        challenge = "Ligand Pose"
    elif "pIC50 (MERS-CoV Mpro)" and "pIC50 (SARS-CoV-2 Mpro)" in sub.keys():
        challenge = "Potency"
    elif "HLM" and "MLM" in sub.keys():
        challenge = "ADMET"
    else:
        raise ValueError()
    return challenge

In [4]:
from evaluation.ligand_poses import evaluate_all_ligand_pose_predictions

In [5]:
submissions["subchallenge"] = submissions["predictions"].apply(determine_subchallenge)
submissions["predictions_unnested"] = submissions["predictions"].apply(lambda x: x["test"])

In [6]:
poses_submissions = submissions.query("subchallenge == 'Ligand Pose'")

In [7]:
for _, entry in poses_submissions.iterrows():
    print(entry["id"], entry["name"], "%%%", entry["description"], "%%%", entry["github_url"], "%%%", entry["report_url"], "\n")

competition-prediction-8oFF30AHg20eUKrnRQzUE asap-gnina-docking-baseline %%% Baseline docking for model comparison (both targets) %%% None %%% https://github.com/asapdiscovery/asap-polaris-challenge-baselines

competition-prediction-Edd645cpFboFZRsUm20em protocol2 %%%  %%% None %%% https://docs.google.com/document/d/1QujhEKtMpdUwFxE_AVq6RBzsHEh4gjkd/edit?usp=sharing&ouid=102900202710669481806&rtpof=true&sd=true

competition-prediction-tXLnHU72dFljtgWAuvh8Z openfe-newcastle-edinburgh-mcs-fegrow %%% FEGrow with mcs core structure finder. %%% https://github.com/jthorton/polaris_fegrow_mcs %%% https://github.com/jthorton/polaris_fegrow_mcs

competition-prediction-late-im0HtqthslCqgR1BHgf9b asap-boltz-1-submission %%% Boltz aligned ligand poses %%% None %%% https://apricot-zorah-51.tiiny.site

competition-prediction-sqr7BVpSxy4NSgljcEgl8 dodo-poses-submission %%% Submission generated using easydock pipeline with substructure alignment %%% https://github.com/fulopjoz/polaris-antiviral-submission %%% https://tinyurl.com/dodo-poses

competition-prediction-t4heZQ05hXlJ6vcfhZjP2 frag_cross_docking %%% complete method with updated workflow %%% https://github.com/KSUN63/Polaris-Submission %%% https://docs.google.com/document/d/1YVxVi-zMc7rX0TrvO7SIZfkQ-uUx3ChdtV4oovq80ts/edit?usp=sharing

competition-prediction-GL85gNve6u38L33Q2wUiJ prediction-gnina-16-64-hybrid %%% report is still a WIP, but should be available at the report_url real soon now. %%% https://github.com/alpha29/polaris-asap-poses %%% https://github.com/alpha29/polaris-asap-poses/blob/master/doc/report.md

competition-prediction-Kec3G0H9KJGWfRouaHDLQ MCES_alignment3 %%% Source code and report will be made public once challenge is finished %%% https://github.com/dehaenw/polaris-baseline %%% https://molecular.beauty/blog/2025/03/13/polaris.html

competition-prediction-JPiM6etVV4SNygnvAZqj7 Pose-Prediction-Intermediate-2-Fixed-Alignment-Issue %%% Apologies, the last submission had alignment mistake. I am now following the latest alignment updates. Please consider this as my final intermediate leaderboard submission. %%% https://github.com/meyresearch/polaris_challenge %%% https://github.com/meyresearch/BoltzForPolaris/blob/250e0b89d9e289b9a42c9edb580cf5f73cac721d/Polaris_Report.pdf

competition-prediction-M0ePYflVVxiF79RnRcCkC newcastle-edinburgh-fegrow %%% FEgrow submission by Finlay Clark, Asma Feriel Khoualdi, Josh Horton, Julien Michel and Daniel Cole (v2) %%% https://github.com/cole-group/FEgrow %%% https://github.com/cole-group/polaris-fegrow

competition-prediction-S9yhyrYVraSy6vZ3u0iwS deltalinf9_clf %%% final_submission %%% https://github.com/XDaiNYU/ %%% https://docs.google.com/document/d/e/2PACX-1vQueWu4Myu0YAguHKRHMX88y7vl4_8z-6_2Y0UXNxt0Ny3kEtyDSwjlsg6soVXOtLfnHnyqmK-WrLWH/pub

competition-prediction-pxXgSbG31dfMbqohnMnfP my_model %%%  %%% None %%% https://docs.google.com/document/d/1SGw3gklEnCv-n_zV3mRvpl4sok304032/edit?usp=sharing&ouid=102900202710669481806&rtpof=true&sd=true

competition-prediction-DLGeSzUxB29MqK9pnBawM asap-oe-docking-baseline %%% Baseline docking for model comparison %%% None %%% https://github.com/asapdiscovery/asap-polaris-challenge-baselines

competition-prediction-8ygjELYPeCo3or8AS6Xom submission1 %%%  %%% None %%% https://colab.research.google.com/drive/1lne8e6-4gkNb3HwocvWBOH6NUBX0svc4?usp=sharing

competition-prediction-o8n3Fgdevuj8th3FfUNu1 final-predictions %%%  %%% https://github.com/ellenaj0/polaris-challenge-ligand-poses-2025 %%% https://drive.google.com/file/d/1leKiDHVeGDe5GL0_ll8fxZrDh05d4X7g/view?usp=sharing

competition-prediction-TPDYWfhEw4nYp81Kd5s1W my-second-predictions %%% Submission for ligand pose %%% https://github.com/cedenoruel/sub_antiviral25 %%% https://github.com/cedenoruel/sub_antiviral25

competition-prediction-th7lSmtpv1tMxmNjYqCJU my-second-predictions-for-pose %%%  %%% None %%% https://github.com/yul533/polaris-antiviral-challenge/blob/main/pose%20prediction

competition-prediction-kMD7A97Q9b7wnRH8Ze9e9 250309v3 %%%  %%% None %%% https://github.com/ryusei-ogino/antiviral-challenge

competition-prediction-TSWQyQgwNyUbdp5EaGbmU newcastle-edinburgh-fegrow-a3fe-equilibrated-no-training %%% FEgrow/A3FE submission by Finlay Clark, Asma Feriel Khoualdi, Josh Horton, Julien Michel and Daniel Cole (v2). No training data were used. %%% https://github.com/michellab/polaris-poses-challenge-fegrow-a3fe %%% https://github.com/michellab/polaris-poses-challenge-fegrow-a3fe

competition-prediction-SXMdEmccFmbNBtiVCZvp9 protocol1 %%%  %%% None %%% https://docs.google.com/document/d/1e4ot7699vR7WfHQoaUXe7tRv7gN127Eu/edit?usp=sharing&ouid=102900202710669481806&rtpof=true&sd=true

competition-prediction-JLy17Fu87yM2ch741quDp my-second-predictions-for-pose %%%  %%% None %%% https://github.com/yul533/polaris-antiviral-challenge/blob/main/pose%20prediction%202

competition-prediction-MoEWcKkwYkPeFHrw3qaWd yzma-first-predictions-VINA-mmff94-25-fix152 %%% Just testing the Polaris API here! %%% https://github.com/myzzzz6 %%% https://www.quantabricks.xyz

competition-prediction-sKvyY8FZzDDX1jaFpBG8t ernestglukhov_266 %%%  %%% None %%% https://docs.google.com/document/d/1ZscH4iBQFIDemyQVkfVfAevUrpPBmJ-vUiBYwwhMAK0/edit?usp=sharing

competition-prediction-GZRD1499Q0k3ejSX7wR22 Predictions_for_OICR_QuAccel %%%  %%% None %%% https://docs.google.com/document/d/1exokoYptuwRllvnQp_S42ZW3ecDc6zdk/edit?usp=sharing&ouid=111958341380201258210&rtpof=true&sd=true

In [8]:
entry_categories = {
    "competition-prediction-8oFF30AHg20eUKrnRQzUE": "CF",
    "competition-prediction-Edd645cpFboFZRsUm20em": "DL",
    "competition-prediction-tXLnHU72dFljtgWAuvh8Z": "PB",
    "competition-prediction-late-im0HtqthslCqgR1BHgf9b": "CF",
    "competition-prediction-sqr7BVpSxy4NSgljcEgl8": "PB",
    "competition-prediction-t4heZQ05hXlJ6vcfhZjP2": "PB",
    "competition-prediction-GL85gNve6u38L33Q2wUiJ": "DL",
    "competition-prediction-Kec3G0H9KJGWfRouaHDLQ": "PB",
    "competition-prediction-JPiM6etVV4SNygnvAZqj7": "CF",
    "competition-prediction-M0ePYflVVxiF79RnRcCkC": "PB",
    "competition-prediction-S9yhyrYVraSy6vZ3u0iwS": "DL",
    "competition-prediction-pxXgSbG31dfMbqohnMnfP": "CF",
    "competition-prediction-DLGeSzUxB29MqK9pnBawM": "PB",
    "competition-prediction-8ygjELYPeCo3or8AS6Xom": "DL",
    "competition-prediction-o8n3Fgdevuj8th3FfUNu1": "DL",
    "competition-prediction-TPDYWfhEw4nYp81Kd5s1W": "PB",
    "competition-prediction-th7lSmtpv1tMxmNjYqCJU": "PB",
    "competition-prediction-kMD7A97Q9b7wnRH8Ze9e": "PB",
    "competition-prediction-TSWQyQgwNyUbdp5EaGbmU": "PB",
    "competition-prediction-SXMdEmccFmbNBtiVCZvp9": "CF",
    "competition-prediction-JLy17Fu87yM2ch741quDp": "PB",
    "competition-prediction-MoEWcKkwYkPeFHrw3qaWd": "PB",
    "competition-prediction-sKvyY8FZzDDX1jaFpBG8t": "CF",
    "competition-prediction-GZRD1499Q0k3ejSX7wR22": "PB",
    'competition-prediction-kMD7A97Q9b7wnRH8Ze9e9': "PB",
}

In [9]:
import pandas as pd
import polaris as po
import base64
import numpy as np

/home/hmacdope/mambaforge/envs/polaris_new2/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [10]:
poses_dataset = po.load_dataset("asap-discovery/antiviral-ligand-poses-2025-unblinded")
poses_data = pd.DataFrame(poses_dataset[:])

/home/hmacdope/mambaforge/envs/polaris_new2/lib/python3.10/site-packages/rich/live.py:256: UserWarning: install
"ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

[2025-08-25 14:16:48] INFO     The version of Polaris that was used to create the artifact          ]8;id=210212;file:///home/hmacdope/mambaforge/envs/polaris_new2/lib/python3.10/site-packages/polaris/_artifact.py\_artifact.py]8;;\:]8;id=941986;file:///home/hmacdope/mambaforge/envs/polaris_new2/lib/python3.10/site-packages/polaris/_artifact.py#96\96]8;;\
                               (0.11.8.dev4+g40e3b2b.d20250207) is different from the currently
                               installed version of Polaris (0.9.2).

                      WARNING  You're loading data from a remote location. If the dataset is small     ]8;id=914790;file:///home/hmacdope/mambaforge/envs/polaris_new2/lib/python3.10/site-packages/polaris/dataset/_base.py\_base.py]8;;\:]8;id=346751;file:///home/hmacdope/mambaforge/envs/polaris_new2/lib/python3.10/site-packages/polaris/dataset/_base.py#187\187]8;;\
                               enough, consider caching the dataset first using DatasetV2.cache() for
                               more performant data access.

[14:16:48]  Success: Fetching dataset                                                                 ]8;id=32847;file:///home/hmacdope/mambaforge/envs/polaris_new2/lib/python3.10/site-packages/polaris/utils/context.py\context.py]8;;\:]8;id=418669;file:///home/hmacdope/mambaforge/envs/polaris_new2/lib/python3.10/site-packages/polaris/utils/context.py#53\53]8;;\

In [11]:
poses_test = poses_data.query("Set == 'Test'")

In [12]:
poses_test

,CXSMILES,Chain A Sequence,Chain B Sequence,Complex Structure,Ligand Pose,Protein Label,Protein Structure,Set
770,O=C1c2ccc(Cl)cc2[C@@]2(CN1Cc1nnco1)C(=O)N(c1cn...,SGLVKMSHPSGDVEACMVQVTCGSMTLNGLWLDNTVWCPRHVMCPA...,SGLVKMSHPSGDVEACMVQVTCGSMTLNGLWLDNTVWCPRHVMCPA...,[ A 1 SER N N -2.080 ...,<rdkit.Chem.rdchem.Mol object at 0x7ee23044eca0>,MERS-CoV Mpro,[ A 1 SER N N -2.080 ...,Test
771,COc1ccc(N(Cc2cccc(Cl)c2)C(=O)Cc2cncc3ccccc23)cc1,SGLVKMSHPSGDVEACMVQVTCGSMTLNGLWLDNTVWCPRHVMCPA...,SGLVKMSHPSGDVEACMVQVTCGSMTLNGLWLDNTVWCPRHVMCPA...,[ A 1 SER N N -1.844 ...,<rdkit.Chem.rdchem.Mol object at 0x7ee23024ecf0>,MERS-CoV Mpro,[ A 1 SER N N -1.844 ...,Test
772,CNC(=O)CN1C[C@@]2(C(=O)N(c3cncc4ccccc34)C[C@@H...,SGFRKMAFPSGKVEGCMVQVTCGTTTLNGLWLDDVVYCPRHVICTS...,SGFRKMAFPSGKVEGCMVQVTCGTTTLNGLWLDDVVYCPRHVICTS...,[ A 1 SER N N 1.620 ...,<rdkit.Chem.rdchem.Mol object at 0x7ee23024ed40>,SARS-CoV-2 Mpro,[ A 1 SER N N 1.620 ...,Test
773,CNC(=O)CN1C[C@@]2(C(=O)N(c3cncc4ccccc34)C[C@@H...,SGLVKMSHPSGDVEACMVQVTCGSMTLNGLWLDNTVWCPRHVMCPA...,SGLVKMSHPSGDVEACMVQVTCGSMTLNGLWLDNTVWCPRHVMCPA...,[ A 1 SER N N -1.775 ...,<rdkit.Chem.rdchem.Mol object at 0x7ee23044ed90>,MERS-CoV Mpro,[ A 1 SER N N -1.775 ...,Test
774,O=C1c2ccc(Cl)cc2[C@@]2(CN1Cc1ccnnc1)C(=O)N(c1c...,SGLVKMSHPSGDVEACMVQVTCGSMTLNGLWLDNTVWCPRHVMCPA...,SGLVKMSHPSGDVEACMVQVTCGSMTLNGLWLDNTVWCPRHVMCPA...,[ A 1 SER N N -1.955 ...,<rdkit.Chem.rdchem.Mol object at 0x7ee23024ede0>,MERS-CoV Mpro,[ A 1 SER N N -1.955 ...,Test
...,...,...,...,...,...,...,...,...
960,CNS(=O)(=O)OCC(=O)N[C@@H](C)c1cc(Cl)cc(-c2ccc(...,SGFRKMAFPSGKVEGCMVQVTCGTTTLNGLWLDDVVYCPRHVICTS...,SGFRKMAFPSGKVEGCMVQVTCGTTTLNGLWLDDVVYCPRHVICTS...,[ A 1 SER N N 1.837 ...,<rdkit.Chem.rdchem.Mol object at 0x7ee21bd90900>,SARS-CoV-2 Mpro,[ A 1 SER N N 1.837 ...,Test
961,CNC(=O)CN1C[C@@]2(C(=O)N(c3cncc4ccccc34)C[C@@H...,SGFRKMAFPSGKVEGCMVQVTCGTTTLNGLWLDDVVYCPRHVICTS...,SGFRKMAFPSGKVEGCMVQVTCGTTTLNGLWLDDVVYCPRHVICTS...,[ A 1 SER N N 1.656 ...,<rdkit.Chem.rdchem.Mol object at 0x7ee230130950>,SARS-CoV-2 Mpro,[ A 1 SER N N 1.656 ...,Test
962,O=C(Cc1cncc2ccccc12)NCc1cccc(Cl)c1,SGLVKMSHPSGDVEACMVQVTCGSMTLNGLWLDNTVWCPRHVMCPA...,SGLVKMSHPSGDVEACMVQVTCGSMTLNGLWLDNTVWCPRHVMCPA...,[ A 1 SER N N -1.700 ...,<rdkit.Chem.rdchem.Mol object at 0x7ee21bd909a0>,MERS-CoV Mpro,[ A 1 SER N N -1.700 ...,Test
963,CNC(=O)CN1C[C@@]2(C(=O)N(c3cncc4ccccc34)C[C@@H...,SGFRKMAFPSGKVEGCMVQVTCGTTTLNGLWLDDVVYCPRHVICTS...,SGFRKMAFPSGKVEGCMVQVTCGTTTLNGLWLDDVVYCPRHVICTS...,[ A 1 SER N N 1.532 ...,<rdkit.Chem.rdchem.Mol object at 0x7ee21bd909f0>,SARS-CoV-2 Mpro,[ A 1 SER N N 1.532 ...,Test
964,C[C@@H]1COC[C@@]2(C1)NC(=O)N(c1cncc3ccccc13)C2=O,SGFRKMAFPSGKVEGCMVQVTCGTTTLNGLWLDDVVYCPRHVICTS...,SGFRKMAFPSGKVEGCMVQVTCGTTTLNGLWLDDVVYCPRHVICNY...,[ A 1 SER N N 1.868 ...,<rdkit.Chem.rdchem.Mol object at 0x7ee230130a40>,SARS-CoV-2 Mpro,[ A 1 SER N N 1.868 ...,Test

In [13]:
y_true = poses_test["Ligand Pose"]

In [14]:
poses_submissions = submissions.query("subchallenge == 'Ligand Pose'")

In [15]:
BASELINE_ID = "competition-prediction-DLGeSzUxB29MqK9pnBawM"

In [27]:
poses_compact = poses_submissions[["id", "description", "owner_id", "github_url", "report_url", "subchallenge","predictions_unnested"]].set_index("id")

In [28]:
poses_submissions

,id,created_at,deleted_at,name,slug,description,tags,user_attributes,access,is_certified,...,polaris_version,owner_id,creator_id,competition_id,predictions,results,github_url,report_url,subchallenge,predictions_unnested
71,competition-prediction-8oFF30AHg20eUKrnRQzUE,2025-02-10 08:26:21.265905+00:00,NaT,asap-gnina-docking-baseline,asap-gnina-docking-baseline,Baseline docking for model comparison (both ta...,[baseline],"{'Method': 'GNINA', 'Framework': 'GNINA'}",public,False,...,0.11.7,08WeSmQpKpu2PgqwGJE4J,08WeSmQpKpu2PgqwGJE4J,competition-UkJQVGKUA7TMNwRHVp7nb,{'test': {'Ligand Pose': ['776t3gAAAAAQAAAAAgA...,"[{'scores': {'CLD': 't', 'Average RMSD': '5.72...",None,https://github.com/asapdiscovery/asap-polaris-...,Ligand Pose,{'Ligand Pose': ['776t3gAAAAAQAAAAAgAAAAAAAAAp...
72,competition-prediction-Edd645cpFboFZRsUm20em,2025-03-14 15:22:19.521538+00:00,NaT,protocol2,protocol2,,[],{},public,False,...,0.11.5,17n4gBhVwbscpSR6uaKr0,17n4gBhVwbscpSR6uaKr0,competition-UkJQVGKUA7TMNwRHVp7nb,{'test': {'Ligand Pose': ['776t3gAAAAAQAAAAAgA...,"[{'scores': {'CLD': 'c', 'Average RMSD': '1.43...",None,https://docs.google.com/document/d/1QujhEKtMpd...,Ligand Pose,{'Ligand Pose': ['776t3gAAAAAQAAAAAgAAAAAAAAAp...
73,competition-prediction-tXLnHU72dFljtgWAuvh8Z,2025-03-14 14:38:25.058677+00:00,NaT,openfe-newcastle-edinburgh-mcs-fegrow,openfe-newcastle-edinburgh-mcs-fegrow,FEGrow with mcs core structure finder.,"[FEGrow, ANI, OpenMM, RDKit, Sage, OpenFF]",{'Method': 'Constrained geometry optimisation ...,public,False,...,0.11.9,8nviRySoUqQG71ckPMqLZ,8nviRySoUqQG71ckPMqLZ,competition-UkJQVGKUA7TMNwRHVp7nb,{'test': {'Ligand Pose': ['776t3gAAAAAQAAAAAgA...,"[{'scores': {'CLD': 'i', 'Average RMSD': '5.04...",https://github.com/jthorton/polaris_fegrow_mcs,https://github.com/jthorton/polaris_fegrow_mcs,Ligand Pose,{'Ligand Pose': ['776t3gAAAAAQAAAAAgAAAAAAAAAp...
74,competition-prediction-late-im0HtqthslCqgR1BHgf9b,2025-03-14 19:00:54.136020+00:00,NaT,asap-boltz-1-submission,asap-boltz-1-submission,Boltz aligned ligand poses,[],{},public,False,...,0.2.5,AznJ6im1Lg9ikYiKBahma,AznJ6im1Lg9ikYiKBahma,competition-UkJQVGKUA7TMNwRHVp7nb,{'test': {'Ligand Pose': ['776t3gAAAAAQAAAAAQA...,"[{'scores': {'CLD': 'd', 'Average RMSD': '1.54...",None,https://apricot-zorah-51.tiiny.site,Ligand Pose,{'Ligand Pose': ['776t3gAAAAAQAAAAAQAAAAAAAAAp...
75,competition-prediction-sqr7BVpSxy4NSgljcEgl8,2025-03-07 10:09:00.275574+00:00,NaT,dodo-poses-submission,dodo-poses-submission,Submission generated using easydock pipeline w...,[],{'Method': 'Docking with substructure alignmen...,public,False,...,0.11.9,C7ibMkBrX6uTYUKUyMANu,C7ibMkBrX6uTYUKUyMANu,competition-UkJQVGKUA7TMNwRHVp7nb,{'test': {'Ligand Pose': ['776t3gAAAAAQAAAAAgA...,"[{'scores': {'CLD': 'p', 'Average RMSD': '4.37...",https://github.com/fulopjoz/polaris-antiviral-...,https://tinyurl.com/dodo-poses,Ligand Pose,{'Ligand Pose': ['776t3gAAAAAQAAAAAgAAAAAAAAAp...
76,competition-prediction-t4heZQ05hXlJ6vcfhZjP2,2025-03-14 10:26:48.082601+00:00,NaT,frag_cross_docking,frag-cross-docking,complete method with updated workflow,[],{'Method': 'Docking with enhanced sampled prot...,public,False,...,0.11.7,DXCx5ew2mA9psvLPwBYmv,DXCx5ew2mA9psvLPwBYmv,competition-UkJQVGKUA7TMNwRHVp7nb,{'test': {'Ligand Pose': ['776t3gAAAAAQAAAAAgA...,"[{'scores': {'CLD': 'h', 'Average RMSD': '2.64...",https://github.com/KSUN63/Polaris-Submission,https://docs.google.com/document/d/1YVxVi-zMc7...,Ligand Pose,{'Ligand Pose': ['776t3gAAAAAQAAAAAgAAAAAAAAA/...
77,competition-prediction-GL85gNve6u38L33Q2wUiJ,2025-03-14 08:39:04.703780+00:00,NaT,prediction-gnina-16-64-hybrid,prediction-gnina-16-64-hybrid,"report is still a WIP, but should be available...",[antiviral-ligand-poses-2025],"{'Method': 'gnina', 'Framework': 'RDKit'}",public,False,...,0.11.9,EyQzTVYVcrgU5kRN3Qg6R,EyQzTVYVcrgU5kRN3Qg6R,competition-UkJQVGKUA7TMNwRHVp7nb,{'test': {'Ligand Pose': ['776t3gAAAAAQAAAAAgA...,"[{'scores': {'CLD': 'u', 'Average RMSD': '6.41...",https://github.com/alpha29/polaris-asap-poses,https://github.com/alpha29/polaris-asap-poses/...,Ligand Pose,{'Ligand Pose': ['776t3gAAAAAQAAAAAgAAAAAAAAAp...
78,competition-prediction-Kec3G0H9KJGWfRouaHDLQ,2025-03-12 17:12:30.698107+00:00,NaT,MCES_alignment3,mces-alignment3,Source code and report will be made public onc...,[],{'Method': 'MCES constained embedding. pose se...,public,False,...,0.11.9,MJfl29Yy4boyjo7TzpRHq,MJfl29Yy4boyjo7TzpRHq,competition-UkJQVGKUA7TMNwRHVp7nb,{'test': {'Ligand Pose': ['776t3gAAAAAQAAAAAgA...,"[{'scores': {'CLD': 'm', 'Average RMSD': '3.17...",https://github.com/dehaenw/polaris-baseline,https://molecular.beauty/blog/2025/03/13/polar...,Ligand Pose,{'Ligand Pose': ['776t3gAAAAAQAAAAAgAAAAAAAAA/...
79,competition-prediction-JPiM6etVV4SNygnvAZqj7,2025-02-27 02:03:54.722321+00:00,NaT,Pose-Prediction-Intermediate-2-Fixed-Alignment...,pose-prediction-intermediate-2-fixed-alignment...,"Apologies, the last submission had alignment m...",[],{},public,False,...,0.11.7,N5cBC3h77rgaJUgNRLPcX,N5cBC3h77rgaJUgNRLPcX,competition-UkJQVGKUA7TMNwRHVp7nb,{'test': {'Ligand Pose': ['776t3gAAAAAQAAAAAgA...,"[{'scores': {'CLD': 'e', 'Average RMSD': '5.04...",https://github.com/meyresearch/polaris_challenge,https://github.com/meyresearch/BoltzForPolaris...,Ligand Pose,{'Ligand Pose': ['776t3gAAAAAQAAAAAgAAAAAAAAAp...
80,competition-prediction-M0ePYflVVxiF79RnRcCkC,2025-03-06 15:41:30.346679+00:00,NaT,newcastle-edinburgh-fegrow,newcastle-edinburgh-fegrow,"FEgrow submission by Finlay Clark, Asma Feriel...","[FEgrow, ANI, OpenMM, RDKit]",{'Method': 'Constrained geometry optimisation ...,public,False,...,0.11.0,NgbkxDCwWNBJAwcRGKNhV,NgbkxDCwWNBJAwcRGKNhV,competition-UkJQVGKUA7TMNwRHVp7nb,{'test': {'Ligand Pose': ['776t3gAAAAAQAAAAAgA...,"[{'scores': {'CLD': 'j', 'Average RMSD': '2.77...",https://github.com/cole-group/FEgrow,https://github.com/cole-group/polaris-fegrow,Ligand Pose,{'Ligand Pose': ['776t3gAAAAAQAAAAAgAAAAAAAAAp...
81,competition-prediction-S9yhyrYVraSy6vZ3u0iwS,2025-03-13 09:51:40.355513+00:00,NaT,deltalinf9_clf,deltalinf9-clf,final_submission,[tutorial],"{'Method': 'Dummy Baseline', 'Framework': 'RDK...",public,False,...,0.11.7,P0R6K9oBc9Lk6MX0ozLG0,P0R6K9oBc9Lk6MX0ozLG0,competition-UkJQVGKUA7TMNwRHVp7nb,{'test': {'Ligand Pose': ['776t3gAAAAAQAAAAAQA...,"[{'scores': {'CLD': 'n', 'Average RMSD': '5.66...",https://github.com/XDaiNYU/,https://docs.google.com/document/d/e/2PACX-1vQ...,Ligand Pose,{'Ligand Pose': ['776t3gAAAAAQAAAAAQAAAAAAAAAp...
82,competition-prediction-pxXgSbG31dfMbqohnMnfP,2025-03-14 15:08:33.642959+00:00,NaT,my_model,my-model,,[],{},public,False,...,0.11.5,RWJ9Ts7Jr5r9iox90zc6n,RWJ9Ts7Jr5r9iox90zc6n,competition-UkJQVGKUA7TMNwRHVp7nb,{'test': {'Ligand Pose': ['776t3gAAAAAQAAAAAgA...,"[{'scores': {'CLD': 'a', 'Average RMSD': '1.33...",None,https://docs.google.com/document/d/1SGw3gklEnC...,Ligand Pose,{'Ligand Pose': ['776t3gAAAAAQAAAAAgAAAAAAAAAp...
83,competition-prediction-DLGeSzUxB29MqK9pnBawM,2025-02-04 05:49:04.919540+00:00,NaT,asap-oe-docking-baseline,asap-oe-docking-baseline,Baseline docking for model comparison,[baseline],"{'Method': 'POSIT', 'Framework': 'OpenEye'}",public,False,...,0.11.6,VZ7vz7oFPTXHUcmrVZ9Ef,VZ7vz7oFPTXHUcmrVZ9Ef,competition-UkJQVGKUA7TMNwRHVp7nb,{'test': {'Ligand Pose': ['776t3gAAAAAQAAAAAQA...,"[{'scores': {'CLD': 'f', 'Average RMSD': '2.21...",None,https://github.com/asapdiscovery/asap-polaris-...,Ligand Pose,{'Ligand Pose': ['776t3gAAAAAQAAAAAQAAAAAAAAA/...
84,competition-prediction-8ygjELYPeCo3or8AS6Xom,2025-03-03 10:33:26.321579+00:00,NaT,submission1,submission1,,[],{},public,False,...,0.11.9,YQtH09KRfpEPtMQBlwTZ5,YQtH09KRfpEPtMQBlwTZ5,competition-UkJQVGKUA7TMNwRHVp7nb,{'test': {'Ligand Pose': ['776t3gAAAAAQAAAAAgA...,"[{'scores': {'CLD': 'w', 'Average RMSD': '24.2...",None,https://colab.research.google.com/drive/1lne8e...,Ligand Pose,{'Ligand Pose': ['776t3gAAAAAQAAAAAgAAAAAAAAA/...
85,competition-prediction-o8n3Fgdevuj8th3FfUNu1,2025-03-09 14:36:51.397166+00:00,NaT,final-predictions,final-predictions,,[],{},public,False,...,0.11.9,cKkY8Snz1vyp85vXbN14T,pzGgQxPbqE7q8lyZRlux9,competition-UkJQVGKUA7TMNwRHVp7nb,{'test': {'Ligand Pose': ['776t3gAAAAAQAAAAAgA...,"[{'scores': {'CLD': 'v', 'Average RMSD': '22.4...",https://github.com/ellenaj0/polaris-challenge-...,https://drive.google.com/file/d/1leKiDHVeGDe5G...,Ligand Pose,{'Ligand Pose': ['776t3gAAAAAQAAAAAgAAAAAAAAAp...
86,competition-prediction-TPDYWfhEw4nYp81Kd5s1W,2025-03-02 18:20:19.445886+00:00,NaT,my-second-predictions,my-second-predictions,Submission for ligand pose,[challenge],"{'Method': 'Docking', 'Framework': 'Docking'}",public,False,...,0.11.8,e61Ug2RA00XPvxYw2DprH,e61Ug2RA00XPvxYw2DprH,competition-UkJQVGKUA7TMNwRHVp7nb,{'test': {'Ligand Pose': ['776t3gAAAAAPAAAAAAA...,"[{'scores': {'CLD': 'g', 'Average RMSD': '2.33...",https://github.com/cedenoruel/sub_antiviral25,https://github.com/cedenoruel/sub_antiviral25,Ligand Pose,{'Ligand Pose': ['776t3gAAAAAPAAAAAAAAAAAAAAAp...
87,competition-prediction-th7lSmtpv1tMxmNjYqCJU,2025-03-14 15:48:56.449073+00:00,NaT,my-second-predictions-for-pose,my-second-predictions-for-pose,,[],{},public,False,...,0.11.8,eBmW8PytUKVz5aPNwvoaD,eBmW8PytUKVz5aPNwvoaD,competition-UkJQVGKUA7TMNwRHVp7nb,{'test': {'Ligand Pose': ['776t3gAAAAAQAAAAAgA...,"[{'scores': {'CLD': 'o', 'Average RMSD': '23.3...",None,https://github.com/yul533/polaris-antiviral-ch...,Ligand Pose,{'Ligand Pose': ['776t3gAAAAAQAAAAAgAAAAAAAAAp...
88,competition-prediction-kMD7A97Q9b7wnRH8Ze9e9,2025-03-09 08:52:28.218903+00:00,NaT,250309v3,250309v3,,[],{},public,False,...,0.11.0,eMRtFW5PzzZa0LbzrYSX0,eMRtFW5PzzZa0LbzrYSX0,competition-UkJQVGKUA7TMNwRHVp7nb,{'test': {'Ligand Pose': ['776t3gAAAAAQAAAAAgA...,"[{'scores': {'CLD': 'l', 'Average RMSD': '25.7...",None,https://github.com/ryusei-ogino/antiviral-chal...,Ligand Pose,{'Ligand Pose': ['776t3gAAAAAQAAAAAgAAAAAAAAAp...
89,competition-prediction-TSWQyQgwNyUbdp5EaGbmU,2025-03-05 07:15:22.055473+00:00,NaT,newcastle-edinburgh-fegrow-a3fe-equilibrated-n...,newcastle-edinburgh-fegrow-a3fe-equilibrated-n...,"FEgrow/A3FE submission by Finlay Clark, Asma F...","[FEgrow, ANI, OpenMM, ABFE, A3FE, MD]",{'Method': 'Constrained geometry optimisation ...,public,False,...,0.11.8,eMchc3woQTPfrqaoQFqat,eMchc3woQTPfrqaoQFqat,competition-UkJQVGKUA7TMNwRHVp7nb,{'test': {'Ligand Pose': ['776t3gAAAAAQAAAAAQA...,"[{'scores': {'CLD': 'q', 'Average RMSD': '3.83...",https://github.com/michellab/polaris-poses-cha...,https://github.com/michellab/polaris-poses-cha...,Ligand Pose,{'Ligand Pose': ['776t3gAAAAAQAAAAAQAAAAAAAAAp...
90,competition-prediction-SXMdEmccFmbNBtiVCZvp9,2025-03-14 15:17:26.874674+00:00,NaT,protocol1,protocol1,,[],{},public,False,...,0.11.5,hVNPTQAK92Rrggu5isbws,hVNPTQAK92Rrggu5isbws,competition-UkJQVGKUA7TMNwRHVp7nb,{'test': {'Ligand Pose': ['776t3gAAAAAQAAAAAgA...,"[{'scores': {'CLD': 'b', 'Average RMSD': '1.38...",None,https://docs.google.com/document/d/1e4ot7699vR...,Ligand Pose,{'Ligand Pose': ['776t3gAAAAAQAAAAAgAAAAAAAAAp...
91,competition-prediction-JLy17Fu87yM2ch741quDp,2025-03-14 15:58:04.273527+00:00,NaT,my-second-predictions-for-pose,my-second-predictions-for-pose,,[],{},public,False,...,0.11.9,kY9WTSWZwwdmKjednWcYW,kY9WTSWZwwdmKjednWcYW,competition-UkJQVGKUA7TMNwRHVp7nb,{'test': {'Ligand Pose': ['776t3gAAAAAQAAAAAgA...,"[{'scores': {'CLD': 's', 'Average RMSD': '21.1...",None,https://github.com/yul533/polaris-antiviral-ch...,Ligand Pose,{'Ligand Pose': ['776t3gAAAAAQAAAAAgAAAAAAAAAp...
92,competition-prediction-MoEWcKkwYkPeFHrw3qaWd,2025-03-14 13:43:49.815604+00:00,NaT,yzma-first-predictions-VINA-mmff94-25-fix152,yzma-first-predictions-vina-mmff94-25-fix152,Just testing the Polaris API here!,[tutorial],"{'Method': 'Dummy Baseline', 'Framework': 'RDK...",public,False,...,0.11.8,rrBijer4tbCuFpkxKQlc9,rrBijer4tbCuFpkxKQlc9,competition-UkJQVGKUA7TMNwRHVp7nb,{'test': {'Ligand Pose': ['776t3gAAAAAQAAAAAgA...,"[{'scores': {'CLD': 'r', 'Average RMSD': '4.93...",https://github.com/myzzzz6,https://www.quantabricks.xyz,Ligand Pose,{'Ligand Pose': ['776t3gAAAAAQAAAAAgAAAAAAAAAp...
93,competition-prediction-sKvyY8FZzDDX1jaFpBG8t,2025-03-10 18:03:33.122171+00:00,NaT,ernestglukhov_266,ernestglukhov-266,,[],{},public,False,...,0.11.5,ugw3LM4bc9zKEmeczKf3e,ugw3LM4bc9zKEmeczKf3e,competition-UkJQVGKUA7TMNwRHVp7nb,{'test': {'Ligand Pose': ['776t3gAAAAAQAAAAAgA...,"[{'scores': {'CLD': 'b', 'Average RMSD': '1.36...",None,https://docs.google.com/document/d/1ZscH4iBQFI...,Ligand Pose,{'Ligand Pose': ['776t3gAAAAAQAAAAAgAAAAAAAAAp...
94,competition-prediction-GZRD1499Q0k3ejSX7wR22,2025-03-13 17:15:19.423094+00:00,NaT,Predictions_for_OICR_QuAccel,predictions-for-oicr-quaccel,,[],{},public,False,...,0.11.5,zpZl5tZ2Rhwhkf8KThNoq,zpZl5tZ2Rhwhkf8KThNoq,competition-UkJQVGKUA7TMNwRHVp7nb,{'test': {'Ligand Pose': ['776t3gAAAAAQAAAAAgA...,"[{'scores': {'CLD': 'k', 'Average RMSD': '3.32...",None,https://docs.google.com/document/d/1exokoYptuw...,Ligand Pose,{'Ligand Pose': ['776t3gAAAAAQAAAAAgAAAAAAAAAp...

In [29]:
from rdkit import Chem

In [30]:
def serialized_list_to_rdkit(data: list[str]) -> list[Chem.Mol]:
    mols = []
    for d in data:
        mols.append(deserialize_rdkit_mol(d))
    return mols
    
def deserialize_rdkit_mol(b64_string: str) -> Chem.Mol:
    mol_bytes = base64.b64decode(b64_string)
    return Chem.Mol(mol_bytes)

In [31]:
poses_compact["predictions_rdkit_mols"] = poses_compact["predictions_unnested"].apply(lambda x: serialized_list_to_rdkit(x["Ligand Pose"]))

In [32]:
poses_compact_dict = poses_compact.to_dict()["predictions_rdkit_mols"]

In [33]:
main, leaderboards = evaluate_all_ligand_pose_predictions(y_true, poses_compact_dict)

Found 275 significantly different pairs

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 275/275 [00:00<00:00, 47759.25it/s]

In [34]:
main

,Method,CLD,mean_rmsd,mean_rmsd_raw,mean_rmsd_std,success_rate,success_rate_raw,success_rate_std
18,competition-prediction-pxXgSbG31dfMbqohnMnfP,a,1.330 ± 0.266,1.329511,0.266044,86.378 ± 2.466,86.377596,2.466433
19,competition-prediction-sKvyY8FZzDDX1jaFpBG8t,b,1.368 ± 0.265,1.367916,0.264880,85.363 ± 2.603,85.362842,2.603348
12,competition-prediction-SXMdEmccFmbNBtiVCZvp9,b,1.388 ± 0.267,1.387794,0.266933,85.213 ± 2.601,85.213115,2.601177
3,competition-prediction-Edd645cpFboFZRsUm20em,c,1.432 ± 0.266,1.431575,0.266270,84.673 ± 2.670,84.673224,2.670313
16,competition-prediction-late-im0HtqthslCqgR1BHgf9b,d,1.549 ± 0.269,1.548972,0.269090,83.657 ± 2.769,83.657377,2.769367
7,competition-prediction-JPiM6etVV4SNygnvAZqj7,e,5.045 ± 0.906,5.044790,0.905610,73.283 ± 3.368,73.283060,3.368103
2,competition-prediction-DLGeSzUxB29MqK9pnBawM,f,2.214 ± 0.287,2.214030,0.287115,67.277 ± 3.453,67.277049,3.453156
13,competition-prediction-TPDYWfhEw4nYp81Kd5s1W,g,2.334 ± 0.276,2.334483,0.276487,62.475 ± 3.583,62.475410,3.583471
21,competition-prediction-t4heZQ05hXlJ6vcfhZjP2,h,2.647 ± 0.286,2.646826,0.286095,53.138 ± 3.686,53.138251,3.685566
22,competition-prediction-tXLnHU72dFljtgWAuvh8Z,i,5.046 ± 0.774,5.045802,0.774471,48.136 ± 3.703,48.136066,3.703007
9,competition-prediction-M0ePYflVVxiF79RnRcCkC,j,2.772 ± 0.284,2.772060,0.284383,47.176 ± 3.767,47.175956,3.767136
5,competition-prediction-GZRD1499Q0k3ejSX7wR22,k,3.320 ± 0.290,3.319919,0.290471,40.984 ± 3.657,40.983607,3.656991
15,competition-prediction-kMD7A97Q9b7wnRH8Ze9e9,l,25.794 ± 1.794,25.793577,1.793567,40.028 ± 3.720,40.027869,3.719876
8,competition-prediction-Kec3G0H9KJGWfRouaHDLQ,m,3.175 ± 0.275,3.174684,0.274688,34.553 ± 3.600,34.553005,3.599827
11,competition-prediction-S9yhyrYVraSy6vZ3u0iwS,n,5.660 ± 0.547,5.660119,0.547340,29.415 ± 3.204,29.415301,3.203951
23,competition-prediction-th7lSmtpv1tMxmNjYqCJU,o,23.374 ± 1.690,23.373885,1.690226,25.785 ± 3.171,25.785246,3.171269
20,competition-prediction-sqr7BVpSxy4NSgljcEgl8,p,4.373 ± 0.284,4.373261,0.283748,22.442 ± 2.990,22.442077,2.990434
14,competition-prediction-TSWQyQgwNyUbdp5EaGbmU,q,3.834 ± 0.280,3.834085,0.279974,18.548 ± 2.915,18.548087,2.914582
10,competition-prediction-MoEWcKkwYkPeFHrw3qaWd,r,4.936 ± 0.297,4.936415,0.297452,17.391 ± 2.778,17.390710,2.778312
6,competition-prediction-JLy17Fu87yM2ch741quDp,s,21.171 ± 1.625,21.170994,1.625258,16.349 ± 2.668,16.348634,2.668498
0,competition-prediction-8oFF30AHg20eUKrnRQzUE,t,5.727 ± 0.272,5.726507,0.271862,2.681 ± 1.161,2.681421,1.160847
4,competition-prediction-GL85gNve6u38L33Q2wUiJ,u,6.418 ± 0.248,6.417972,0.247671,2.174 ± 1.089,2.173770,1.088994
17,competition-prediction-o8n3Fgdevuj8th3FfUNu1,v,22.416 ± 1.397,22.415996,1.396757,1.110 ± 0.765,1.109836,0.765027
1,competition-prediction-8ygjELYPeCo3or8AS6Xom,w,24.227 ± 0.047,24.227087,0.046577,0.000 ± 0.000,0.000000,0.000000

In [38]:
main["Type"] = main["Method"].apply(lambda x: entry_categories[x])

/tmp/ipykernel_30724/1607735642.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main["Type"] = main["Method"].apply(lambda x: entry_categories[x])

In [42]:
sub = submissions[["id", "description", "owner_id", "github_url", "report_url", "subchallenge"]]
admet_sub = sub[sub["subchallenge"] == "Ligand Pose"]
users = pd.read_json("./autumn-scene-83598112_main_polaris_2025-03-24_08-43-21.json")
users = users.rename(columns={"id": "owner_id", "slug": "username"})
combined = admet_sub.merge(users, on="owner_id", how="left").rename(columns={"id":"Method"})
all_combined = main.merge(combined, how="left", on="Method")

In [43]:
all_combined

,Method,CLD,mean_rmsd,mean_rmsd_raw,mean_rmsd_std,success_rate,success_rate_raw,success_rate_std,Type,description,owner_id,github_url,report_url,subchallenge,username
0,competition-prediction-pxXgSbG31dfMbqohnMnfP,a,1.330 ± 0.266,1.329511,0.266044,86.378 ± 2.466,86.377596,2.466433,CF,,RWJ9Ts7Jr5r9iox90zc6n,None,https://docs.google.com/document/d/1SGw3gklEnC...,Ligand Pose,averkova-nika98
1,competition-prediction-sKvyY8FZzDDX1jaFpBG8t,b,1.368 ± 0.265,1.367916,0.264880,85.363 ± 2.603,85.362842,2.603348,CF,,ugw3LM4bc9zKEmeczKf3e,None,https://docs.google.com/document/d/1ZscH4iBQFI...,Ligand Pose,ernestglukhov
2,competition-prediction-SXMdEmccFmbNBtiVCZvp9,b,1.388 ± 0.267,1.387794,0.266933,85.213 ± 2.601,85.213115,2.601177,CF,,hVNPTQAK92Rrggu5isbws,None,https://docs.google.com/document/d/1e4ot7699vR...,Ligand Pose,vemikainen
3,competition-prediction-Edd645cpFboFZRsUm20em,c,1.432 ± 0.266,1.431575,0.266270,84.673 ± 2.670,84.673224,2.670313,DL,,17n4gBhVwbscpSR6uaKr0,None,https://docs.google.com/document/d/1QujhEKtMpd...,Ligand Pose,vemikainenalt
4,competition-prediction-late-im0HtqthslCqgR1BHgf9b,d,1.549 ± 0.269,1.548972,0.269090,83.657 ± 2.769,83.657377,2.769367,CF,Boltz aligned ligand poses,AznJ6im1Lg9ikYiKBahma,None,https://apricot-zorah-51.tiiny.site,Ligand Pose,wiwnopgm
5,competition-prediction-JPiM6etVV4SNygnvAZqj7,e,5.045 ± 0.906,5.044790,0.905610,73.283 ± 3.368,73.283060,3.368103,CF,"Apologies, the last submission had alignment m...",N5cBC3h77rgaJUgNRLPcX,https://github.com/meyresearch/polaris_challenge,https://github.com/meyresearch/BoltzForPolaris...,Ligand Pose,auro
6,competition-prediction-DLGeSzUxB29MqK9pnBawM,f,2.214 ± 0.287,2.214030,0.287115,67.277 ± 3.453,67.277049,3.453156,PB,Baseline docking for model comparison,VZ7vz7oFPTXHUcmrVZ9Ef,None,https://github.com/asapdiscovery/asap-polaris-...,Ligand Pose,hmacdope
7,competition-prediction-TPDYWfhEw4nYp81Kd5s1W,g,2.334 ± 0.276,2.334483,0.276487,62.475 ± 3.583,62.475410,3.583471,PB,Submission for ligand pose,e61Ug2RA00XPvxYw2DprH,https://github.com/cedenoruel/sub_antiviral25,https://github.com/cedenoruel/sub_antiviral25,Ligand Pose,rced
8,competition-prediction-t4heZQ05hXlJ6vcfhZjP2,h,2.647 ± 0.286,2.646826,0.286095,53.138 ± 3.686,53.138251,3.685566,PB,complete method with updated workflow,DXCx5ew2mA9psvLPwBYmv,https://github.com/KSUN63/Polaris-Submission,https://docs.google.com/document/d/1YVxVi-zMc7...,Ligand Pose,kysun
9,competition-prediction-tXLnHU72dFljtgWAuvh8Z,i,5.046 ± 0.774,5.045802,0.774471,48.136 ± 3.703,48.136066,3.703007,PB,FEGrow with mcs core structure finder.,8nviRySoUqQG71ckPMqLZ,https://github.com/jthorton/polaris_fegrow_mcs,https://github.com/jthorton/polaris_fegrow_mcs,Ligand Pose,jthorton
10,competition-prediction-M0ePYflVVxiF79RnRcCkC,j,2.772 ± 0.284,2.772060,0.284383,47.176 ± 3.767,47.175956,3.767136,PB,"FEgrow submission by Finlay Clark, Asma Feriel...",NgbkxDCwWNBJAwcRGKNhV,https://github.com/cole-group/FEgrow,https://github.com/cole-group/polaris-fegrow,Ligand Pose,djc56
11,competition-prediction-GZRD1499Q0k3ejSX7wR22,k,3.320 ± 0.290,3.319919,0.290471,40.984 ± 3.657,40.983607,3.656991,PB,,zpZl5tZ2Rhwhkf8KThNoq,None,https://docs.google.com/document/d/1exokoYptuw...,Ligand Pose,kbishop
12,competition-prediction-kMD7A97Q9b7wnRH8Ze9e9,l,25.794 ± 1.794,25.793577,1.793567,40.028 ± 3.720,40.027869,3.719876,PB,,eMRtFW5PzzZa0LbzrYSX0,None,https://github.com/ryusei-ogino/antiviral-chal...,Ligand Pose,ryusei-ogino
13,competition-prediction-Kec3G0H9KJGWfRouaHDLQ,m,3.175 ± 0.275,3.174684,0.274688,34.553 ± 3.600,34.553005,3.599827,PB,Source code and report will be made public onc...,MJfl29Yy4boyjo7TzpRHq,https://github.com/dehaenw/polaris-baseline,https://molecular.beauty/blog/2025/03/13/polar...,Ligand Pose,wim0
14,competition-prediction-S9yhyrYVraSy6vZ3u0iwS,n,5.660 ± 0.547,5.660119,0.547340,29.415 ± 3.204,29.415301,3.203951,DL,final_submission,P0R6K9oBc9Lk6MX0ozLG0,https://github.com/XDaiNYU/,https://docs.google.com/document/d/e/2PACX-1vQ...,Ligand Pose,xuhangdai
15,competition-prediction-th7lSmtpv1tMxmNjYqCJU,o,23.374 ± 1.690,23.373885,1.690226,25.785 ± 3.171,25.785246,3.171269,PB,,eBmW8PytUKVz5aPNwvoaD,None,https://github.com/yul533/polaris-antiviral-ch...,Ligand Pose,yul533
16,competition-prediction-sqr7BVpSxy4NSgljcEgl8,p,4.373 ± 0.284,4.373261,0.283748,22.442 ± 2.990,22.442077,2.990434,PB,Submission generated using easydock pipeline w...,C7ibMkBrX6uTYUKUyMANu,https://github.com/fulopjoz/polaris-antiviral-...,https://tinyurl.com/dodo-poses,Ligand Pose,dodo
17,competition-prediction-TSWQyQgwNyUbdp5EaGbmU,q,3.834 ± 0.280,3.834085,0.279974,18.548 ± 2.915,18.548087,2.914582,PB,"FEgrow/A3FE submission by Finlay Clark, Asma F...",eMchc3woQTPfrqaoQFqat,https://github.com/michellab/polaris-poses-cha...,https://github.com/michellab/polaris-poses-cha...,Ligand Pose,fjclark
18,competition-prediction-MoEWcKkwYkPeFHrw3qaWd,r,4.936 ± 0.297,4.936415,0.297452,17.391 ± 2.778,17.390710,2.778312,PB,Just testing the Polaris API here!,rrBijer4tbCuFpkxKQlc9,https://github.com/myzzzz6,https://www.quantabricks.xyz,Ligand Pose,myzzzz
19,competition-prediction-JLy17Fu87yM2ch741quDp,s,21.171 ± 1.625,21.170994,1.625258,16.349 ± 2.668,16.348634,2.668498,PB,,kY9WTSWZwwdmKjednWcYW,None,https://github.com/yul533/polaris-antiviral-ch...,Ligand Pose,nnnty
20,competition-prediction-8oFF30AHg20eUKrnRQzUE,t,5.727 ± 0.272,5.726507,0.271862,2.681 ± 1.161,2.681421,1.160847,CF,Baseline docking for model comparison (both ta...,08WeSmQpKpu2PgqwGJE4J,None,https://github.com/asapdiscovery/asap-polaris-...,Ligand Pose,jscheen
21,competition-prediction-GL85gNve6u38L33Q2wUiJ,u,6.418 ± 0.248,6.417972,0.247671,2.174 ± 1.089,2.173770,1.088994,DL,"report is still a WIP, but should be available...",EyQzTVYVcrgU5kRN3Qg6R,https://github.com/alpha29/polaris-asap-poses,https://github.com/alpha29/polaris-asap-poses/...,Ligand Pose,vanguard737
22,competition-prediction-o8n3Fgdevuj8th3FfUNu1,v,22.416 ± 1.397,22.415996,1.396757,1.110 ± 0.765,1.109836,0.765027,DL,,cKkY8Snz1vyp85vXbN14T,https://github.com/ellenaj0/polaris-challenge-...,https://drive.google.com/file/d/1leKiDHVeGDe5G...,Ligand Pose,kriegegroup
23,competition-prediction-8ygjELYPeCo3or8AS6Xom,w,24.227 ± 0.047,24.227087,0.046577,0.000 ± 0.000,0.000000,0.000000,DL,,YQtH09KRfpEPtMQBlwTZ5,None,https://colab.research.google.com/drive/1lne8e...,Ligand Pose,sekuen

In [44]:
raw_columns_to_drop = all_combined.filter(regex='raw').columns
std_columns_to_drop = all_combined.filter(regex='std').columns

In [56]:
drop = list(std_columns_to_drop) + list(raw_columns_to_drop) + ["owner_id", "Method", "description", "subchallenge"]

In [65]:
all_combined_filt = all_combined.drop(columns=drop)
# username to first
cols = ["username", "CLD", "Type", "success_rate", "github_url", "report_url"]

In [68]:
all_combined_filt_final = all_combined_filt[cols].rename(columns={"username": "Username", "mean_absolute_error": "MAE", "github_url": "GitHub", "report_url":"Report", "success_rate": "Success Rate"})
all_combined_filt_final.to_csv("poses_SI_table.csv", index=False)

In [69]:
all_combined_filt_final

,Username,CLD,Type,Success Rate,GitHub,Report
0,averkova-nika98,a,CF,86.378 ± 2.466,None,https://docs.google.com/document/d/1SGw3gklEnC...
1,ernestglukhov,b,CF,85.363 ± 2.603,None,https://docs.google.com/document/d/1ZscH4iBQFI...
2,vemikainen,b,CF,85.213 ± 2.601,None,https://docs.google.com/document/d/1e4ot7699vR...
3,vemikainenalt,c,DL,84.673 ± 2.670,None,https://docs.google.com/document/d/1QujhEKtMpd...
4,wiwnopgm,d,CF,83.657 ± 2.769,None,https://apricot-zorah-51.tiiny.site
5,auro,e,CF,73.283 ± 3.368,https://github.com/meyresearch/polaris_challenge,https://github.com/meyresearch/BoltzForPolaris...
6,hmacdope,f,PB,67.277 ± 3.453,None,https://github.com/asapdiscovery/asap-polaris-...
7,rced,g,PB,62.475 ± 3.583,https://github.com/cedenoruel/sub_antiviral25,https://github.com/cedenoruel/sub_antiviral25
8,kysun,h,PB,53.138 ± 3.686,https://github.com/KSUN63/Polaris-Submission,https://docs.google.com/document/d/1YVxVi-zMc7...
9,jthorton,i,PB,48.136 ± 3.703,https://github.com/jthorton/polaris_fegrow_mcs,https://github.com/jthorton/polaris_fegrow_mcs
10,djc56,j,PB,47.176 ± 3.767,https://github.com/cole-group/FEgrow,https://github.com/cole-group/polaris-fegrow
11,kbishop,k,PB,40.984 ± 3.657,None,https://docs.google.com/document/d/1exokoYptuw...
12,ryusei-ogino,l,PB,40.028 ± 3.720,None,https://github.com/ryusei-ogino/antiviral-chal...
13,wim0,m,PB,34.553 ± 3.600,https://github.com/dehaenw/polaris-baseline,https://molecular.beauty/blog/2025/03/13/polar...
14,xuhangdai,n,DL,29.415 ± 3.204,https://github.com/XDaiNYU/,https://docs.google.com/document/d/e/2PACX-1vQ...
15,yul533,o,PB,25.785 ± 3.171,None,https://github.com/yul533/polaris-antiviral-ch...
16,dodo,p,PB,22.442 ± 2.990,https://github.com/fulopjoz/polaris-antiviral-...,https://tinyurl.com/dodo-poses
17,fjclark,q,PB,18.548 ± 2.915,https://github.com/michellab/polaris-poses-cha...,https://github.com/michellab/polaris-poses-cha...
18,myzzzz,r,PB,17.391 ± 2.778,https://github.com/myzzzz6,https://www.quantabricks.xyz
19,nnnty,s,PB,16.349 ± 2.668,None,https://github.com/yul533/polaris-antiviral-ch...
20,jscheen,t,CF,2.681 ± 1.161,None,https://github.com/asapdiscovery/asap-polaris-...
21,vanguard737,u,DL,2.174 ± 1.089,https://github.com/alpha29/polaris-asap-poses,https://github.com/alpha29/polaris-asap-poses/...
22,kriegegroup,v,DL,1.110 ± 0.765,https://github.com/ellenaj0/polaris-challenge-...,https://drive.google.com/file/d/1leKiDHVeGDe5G...
23,sekuen,w,DL,0.000 ± 0.000,None,https://colab.research.google.com/drive/1lne8e...